### ISSUE TITLE
AssignUniqueID dosent work

### ISSUE THREAD

**Issue by sachuriga283** [EnnyvanBeest/UnitMatch#37]
![image](https://github.com/EnnyvanBeest/UnitMatch/assets/49390274/0a2c4afb-75cc-4192-9d04-43d0ae91c76d)
![image](https://github.com/EnnyvanBeest/UnitMatch/assets/49390274/8140c035-0adc-4a81-85f1-7410984112ed)
![image](https://github.com/EnnyvanBeest/UnitMatch/assets/49390274/ebdc98ac-9621-411c-b660-b223fe292d39)

1 As shown in the figure, it seems like two units matched, but they are not being assigned the same ID. This issue occurred not only with the provided data but also with my own data.

2 I am not a Neuropixel/SpikeGLX user, so I have been extracting waveforms manually. However, the preprocessing performed on the original data and the waveform extraction process are unclear. Could you please share details about the processes performed on the waveform?

3 like in para file GoodUnitsOnly was set to 1 but its still including all the units.

**Comment by EnnyvanBeest** [comment]
Hi there,

Thank you for trying out UnitMatch!
1. Assuming you're talking about unit 84 and 99. Can you please check if the other way around they also match? (so that would be 84 of Recording 1, second half versus 99 of recording 2 1st half). In assignuniqueID bot hneed to be >0.5 to be assigned as match. Please note that AssignUniqueID is an example of what you can do with the data, but if you want to set other rules for two units to be the same, feel free to do that based on the table you included. 
2. Extraction is done either as part of the Bombcell package (https://zenodo.org/records/8172822) using the UnitMatch default parameters, or via UnitMatch's ExtractAndSaveAverageWaveform (https://github.com/EnnyvanBeest/UnitMatch/blob/main/UnitMatchPipeline/ExtractAndSaveAverageWaveforms.m). I'm planning to make it work with OpenEphys as soon as possible.
3. How did you define Good Units in your pipeline? i.e. is there a point where you define/load clusinfo.Good_ID? If not they will all be set to 1 and all included. 

Otherwise, if there's a param issue, it might be something that was fixed with the latest push (9th of November). Please consider pulling again if you have a version from before.

**Comment by sachuriga283** [comment]
Thanks！
